
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase';

// These keys will need to be replaced with actual Supabase credentials
const SUPABASE_URL = "https://placeholder-url.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "placeholder-key";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
