// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjuunitqaivtxxtvfxsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqdXVuaXRxYWl2dHh4dHZmeHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTA3MDQsImV4cCI6MjA2MjM4NjcwNH0.qMtSY8WZulgKRgTYXz6VEYeesoxsvxJE748kXwOazng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);